version: '3.8'

services:
  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    env_file:
      - ./BACKEND/.env

  frontend:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
