import json
from google import genai
from google.genai import types
from app.core.config import settings
from app.schemas.kanoon import KanoonQueryRequest, KanoonQueryResponse
from sqlalchemy.orm import Session

class KanoonService:
    def __init__(self):
        # The genai client will automatically pick up GEMINI_API_KEY from environment or it can be passed.
        api_key = settings.GEMINI_API_KEY or "DUMMY_KEY_FOR_TESTING"
        self.client = genai.Client(api_key=api_key)
            
    def query(self, request: KanoonQueryRequest, user_id: str, db: Session, background_tasks) -> KanoonQueryResponse:
        from app.models.chat import Conversation, Message, FeatureType, MessageRole
        from app.ai.orchestrator import rag_orchestrator
        from app.services.title_service import generate_conversation_title_async
        import json
        
        conversation = None
        
        if request.conversation_id:
            conversation = db.query(Conversation).filter(
                Conversation.id == request.conversation_id,
                Conversation.user_id == user_id
            ).first()

            if conversation and conversation.feature_type != FeatureType.know_kanoon:
                raise HTTPException(status_code=400, detail="Conversation does not belong to Know Your Kanoon.")
        
        if not conversation:
            title = "New Conversation"
            conversation = Conversation(
                user_id=user_id,
                title=title,
                feature_type=FeatureType.know_kanoon
            )
            db.add(conversation)
            db.commit()
            db.refresh(conversation)
            
            background_tasks.add_task(generate_conversation_title_async, conversation.id, request.question)

        # Save User Message
        user_msg = Message(
            conversation_id=conversation.id,
            role=MessageRole.user,
            content=request.question
        )
        db.add(user_msg)
        db.commit()

        # Load real history from DB instead of empty array
        past_messages = db.query(Message).filter(Message.conversation_id == conversation.id).order_by(Message.created_at.asc()).all()
        # the history parameter is expecting list of dicts. We skip the very last message which is the current user_msg.
        formatted_history = [{"role": m.role.value, "content": m.content} for m in past_messages[:-1]]

        # Trigger Orchestrator
        filters = {
            "tenant_id": "global" # Only search system documents
        }
        
        response_data = rag_orchestrator.trigger_pipeline(
            question=request.question,
            filters=filters,
            history=formatted_history
        )
        
        # Map Orchestrator response to Kanoon schema
        # We repurpose the "similar_cases" UI section to show RAG citations
        citations = response_data.get("citations", [])
        citations_md = "### Source Documents Retrieved\n\n"
        if not citations:
            citations_md += "No specific legal texts found for this query.\n"
        else:
            for cit in citations:
                source = cit["metadata"].get("source_name", "Unknown Source")
                snippet = cit["text_snippet"].replace('\n', ' ')
                citations_md += f"**{cit['marker']} {source}**: {snippet}\n\n"
        
        raw_answer = response_data.get("answer", "No answer generated.")
        
        import re
        
        # Extract the Executive Summary explicitly if it exists
        # Extract the Executive Summary explicitly if it exists
        exec_summary_match = re.search(r'(?i)##\s*Executive Summary\s*\n(.*?)(?=\n##|\Z)', raw_answer, re.DOTALL)
        if exec_summary_match:
            dynamic_summary = exec_summary_match.group(1).strip()
            # Remove the Executive Summary from the raw_answer to prevent UI duplication
            new_raw_answer = raw_answer[:exec_summary_match.start()] + raw_answer[exec_summary_match.end():]
            if new_raw_answer.strip():
                raw_answer = new_raw_answer.strip()
            else:
                # If removing the summary leaves the answer completely empty, put it back or leave it as is
                raw_answer = dynamic_summary
        else:
            paragraphs = [p.strip() for p in raw_answer.split('\n') if p.strip() and not p.strip().startswith('#')]
            dynamic_summary = paragraphs[0] if paragraphs else "Response generated based on retrieved legal knowledge."
            if len(dynamic_summary) > 250:
                dynamic_summary = dynamic_summary[:247] + "..."

        final_json = {
            "answer": raw_answer,
            "summary": dynamic_summary,
            "similar_cases": citations_md,
            "disclaimer": "This information is generated by AI based on legal documents and does not constitute professional legal advice.",
            "category": "General Legal Query"
        }
        
        # Save Assistant Message
        assistant_msg = Message(
            conversation_id=conversation.id,
            role=MessageRole.assistant,
            content=json.dumps(final_json)
        )
        db.add(assistant_msg)
        db.commit()
        
        return KanoonQueryResponse(conversation_id=conversation.id, **final_json)



kanoon_service = KanoonService()

